[pytest]
addopts =
    --nbmake
    --nbmake-kernel=python3
    --nbmake-timeout=600
    -ra
testpaths =
    tests
    LAB_over_under_fitting.ipynb
    labs
    tutorial
    tutorials
markers =
    notebook_xfail: notebook currently expected to fail in automated execution
